### ISSUE TITLE
Building with system-wide installed Yosys and system-wide installed Surelog

### ISSUE THREAD

**Issue by donn** [chipsalliance/synlig#2079]
There don't appear to be any instructions on building Synlig without cloning and building both Surelog and Yosys as submodules. Is this not possible?

**Comment by alaindargelas** [comment]
The new build process does not allow that.
But if you browse the history at that point:
https://github.com/chipsalliance/synlig/tree/bd3586102ffd9374ad299a61e5f71ede6da341a0

You'll find a build_binaries.sh and corresponding Makefile in the frontend subdirectory.
With a bit of massage you should be a able to create your own Makefile or Cmake that uses the pre-installed Yosys and Surelog and only compile the plugin.
As a matter of fact, when you get that done, please contribute it as an alternative to the vendored build we have now.
Maybe in the form of documentation only.
Both vendored/non-vendored builds have their pros/cons. We only support the vendored build (monolithic) for bandwidth and potential support issues reasons with non-vendored.

**Comment by pgielda** [comment]
Complicated question. The commits in submodules are the "official" ones that we build and test with.
Also we link statically with libsurelog and libuhdm to the plugin.
As for yosys the plugin will work with any new enough yosys, but also since yosys changes frequently we only guarantee it to work with the version we're currently pointing to as the submodule.
It does not mean you cannot try to build it in some other way, but the only official way is the one we have.

**Comment by kgugala** [comment]
we dropped this because it was really hard to maintain it. Distros provide libs and tools in various version (e.g. most distros package pretty old yosys).

There were a few breaking changes in all Yosys, Surelog and UHDM. As far as I remember we dropped the support for build against a packaged tools after one of those breaking changes. We do, however, provide prebuilt plugin (as releases in this repo) and those are tested in CI against yosys packaged in Debian Trixie.

@donn if you find a combination that works and you will be willing to contribute the docs update, please note down the distro version and exact versions of the packaged tools and libs. I think you should be able to get this working in Debian Trixie (as this one provides pretty recent Yosys). Keep in mind that Debian applies this [patch](https://sources.debian.org/patches/yosys/0.33-5/0017-Support-plugin-loading-from-libdir.patch/) harcoding plugins search dir in Yosys, so make sure you install the plugins exactly there. Our [installation script](https://github.com/chipsalliance/synlig/blob/main/install_plugin.sh) takes this int account so you can use it, or copy this logic to your code

**Comment by donn** [comment]
I ended up using a fairly customized Nix-based build, but the essence of it is to:

1. Remove `third_party/Build.surelog.mk`
2. Change `third_party/Build.yosys.mk` to just this:

```Makefile
  t  := yosys
  ts := $(call GetTargetStructName,${t})

  ${ts}.src_dir         := $(shell yosys-config --datdir/include)
  ${ts}.mod_dir         := ${TOP_DIR}third_party/yosys_mod/
```

Then the plugin is simply placed into whatever the path for `/nix/store/swqn94rs1gv5k5mj6v9frclrv7333h08-yosys/share/yosys/plugins` is.
---

For the versions, I used synlig e41b39653b5bc45f464825affa5464473be7b92a with Yosys v0.34 and Surelog v1.76. With `pkg-config` it appeared to be able to find and link against Surelog just fine with the above modifications.

Though it still doesn't compile on macOS, complaining about some Yosys symbols missing. But I suspect that's because `-undefined dynamic_lookup` is missing from the compile.

**Comment by donn** [comment]
Alright, I've got it working on both Linux and macOS with Nix now. Unfortunately, it's a bit too… custom to contribute to the official documentation but I think people with similar niche use-cases can hopefully find this issue and get an idea of what they need to do.

**Comment by donn** [comment]
I mean, it's all here:

https://github.com/efabless/openlane2/blob/support_synlig/nix/yosys-synlig-sv.nix

**Comment by alaindargelas** [comment]
Thanks, good enough!

**Comment by hzeller** [comment]
@donn FYI, I just packaged Synlig last weekend on NixOS https://github.com/NixOS/nixpkgs/pull/261237/files
I also had to do some local makefile hacks to make it compile (e.g. use `yosys-config` in the ldflags).

So with the latest Nix packages unstable (or locally check it out, I think the latest build is [not fully propagated yet](https://status.nixos.org/)), you should be able to use it with

```
  nix-shell -p surelog yosys yosys-synlig
```

**Comment by donn** [comment]
Argh. This would have been very useful a couple days ago. Good to know though. I'm on 23.05 but this should be ready for 23.11 I think.

**Comment by hzeller** [comment]
I should've watched these issues more to respond earlier. Anyway, I like your approach to working around the Makefile issues while I only applied a patch. I'll refine that similar to your approach in my next round.

I am usually a few days behind on unstable, life is too short :)
